version: '3'

services:
  backend:
    
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "dockertestserver:latest"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "dockertestclient:latest"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
      