version: "3"
services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    # Due to stupid react-scripts bug still present in v3.4.3
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules