version: "3"

services:
  app:
    build:
      context: ./app
    environment:
      EXPRESS_HOST: backend

  api:
    build:
      context: ./api
      
    ports:
      - "5000:5000"
    env_file: ./api/.env
    environment:
      HOST: 0.0.0.0
      

 

