FROM node:14

LABEL version="1.0"
LABEL description="This is the base docker image for the uploading files from react frontend to backend."

# ENV NPM_CONFIG_LOGLEVEL warn
# ARG app_env
# ENV APP_ENV $app_env

# RUN mkdir -p /client
WORKDIR /usr/src/app
# COPY . .

# RUN npm install

# CMD if [ ${APP_ENV} = production ]; \
#     then \
#     npm install -g http-server && \
#     npm run build && \
#     cd build && \
#     hs -p 3000; \
#     else \
#     npm run start; \
#     fi
COPY package*.json ./
RUN npm install
EXPOSE 3000 

CMD [ "npm", "run", "start" ]