FROM node:14

LABEL version="1.0"
LABEL description="This is the base docker image for the uploading files from react frontend to backend."

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
EXPOSE 3000 

CMD [ "npm", "run", "start" ]